#!/usr/bin/env python

import logging
import sys
import os
import inspect
from es_cli import ESCLI

cmd_folder = os.path.realpath(os.path.abspath(os.path.split(inspect.getfile( inspect.currentframe()))[0]))
cmd_folder = os.path.realpath(os.path.join(cmd_folder, ".."))
if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


if __name__ == "__main__":

    logging.basicConfig(level=logging.INFO)

    es = ESCLI()
    es.main_cli()
